import { StyleSheet } from 'react-native';
import { useThemeStore } from '@/store/useThemeStore';
import { Colors, Fonts, Spacing, MaxContentWidth, LightColors, DarkColors } from '@/constants/theme';

export function createStyles(Colors: typeof LightColors) {
  const isDark = (Colors.primaryAccent as string) === '#FFFFFF';
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    safeArea: {
      flex: 1,
      alignSelf: 'center',
      width: '100%',
      maxWidth: MaxContentWidth,
    },
    scrollContent: {
      paddingHorizontal: Spacing.four,
      paddingTop: Spacing.two,
      paddingBottom: 120,
      gap: Spacing.four,
    },
    tabSwitcher: {
      flexDirection: 'row',
      backgroundColor: isDark ? Colors.background : '#E2E8F0',
      borderColor: isDark ? Colors.coltsNavyLight : '#CBD5E1',
      borderWidth: 1,
      borderRadius: 10,
      padding: 4,
      minHeight: 46,
      marginHorizontal: Spacing.four,
    },
    tabButton: {
      flex: 1,
      height: 38,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
    },
    tabButtonActive: {
      backgroundColor: Colors.surface,
      borderColor: isDark ? Colors.coltsNavyLight : '#E2E8F0',
      borderWidth: 1,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    tabButtonText: {
      fontFamily: Fonts.headings,
      fontSize: 12,
      color: isDark ? Colors.secondaryAccent : '#64748b',
      letterSpacing: 0.5,
    },
    tabButtonTextActive: {
      color: Colors.primaryAccent,
      fontWeight: 'bold',
    },
    simulatingOverlay: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: isDark ? 'rgba(12, 12, 12, 0.95)' : 'rgba(248, 250, 252, 0.95)',
      zIndex: 999,
      justifyContent: 'center',
      alignItems: 'center',
      gap: Spacing.three,
    },
    simulatingText: {
      fontFamily: Fonts.headings,
      fontSize: 15,
      color: Colors.primaryAccent,
      letterSpacing: 0.5,
    },
    overlayProgressBarBg: {
      width: 240,
      height: 8,
      backgroundColor: Colors.surfaceLifted,
      borderRadius: 4,
      overflow: 'hidden',
      marginTop: Spacing.one,
      borderColor: Colors.coltsNavyLight,
      borderWidth: 1,
    },
    overlayProgressBarFill: {
      height: '100%',
      backgroundColor: Colors.coltsNavy,
      borderRadius: 4,
    },

    // Coach Feedback styles
    coachContainer: {
      gap: Spacing.three,
    },
    coachBubble: {
      backgroundColor: Colors.surface,
      borderColor: Colors.coltsNavyLight,
      borderWidth: 1,
      borderRadius: 12,
      padding: Spacing.four,
      gap: Spacing.two,
      ...Colors.shadows,
    },
    coachTitle: {
      fontFamily: Fonts.headings,
      fontSize: 14,
      color: Colors.secondaryAccent,
      letterSpacing: 0.5,
    },
    coachStatus: {
      fontFamily: Fonts.stats,
      fontSize: 10,
      fontWeight: 'bold',
      letterSpacing: 1.5,
    },
    coachSuccess: {
      color: '#22c55e',
    },
    coachWarning: {
      color: '#eab308',
    },
    coachFeedback: {
      fontFamily: Fonts.body,
      fontSize: 13,
      color: Colors.primaryAccent,
      lineHeight: 18,
      opacity: 0.9,
    },
    coachSubHeader: {
      fontFamily: Fonts.stats,
      fontSize: 9,
      fontWeight: 'bold',
      color: Colors.secondaryAccent,
      letterSpacing: 1,
      marginTop: Spacing.two,
    },
    coachSuggestionItem: {
      fontFamily: Fonts.body,
      fontSize: 12,
      color: Colors.secondaryAccent,
      lineHeight: 16,
    },
    coachSectionTitle: {
      fontFamily: Fonts.stats,
      fontSize: 10,
      color: Colors.secondaryAccent,
      letterSpacing: 1.5,
      marginTop: Spacing.two,
    },
    valueList: {
      gap: 6,
    },
    valueRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.surface,
      borderColor: Colors.coltsNavyLight,
      borderWidth: 1,
      borderRadius: 8,
      paddingVertical: 6,
      paddingHorizontal: Spacing.two,
      gap: Spacing.two,
      height: 58,
    },
    valueRoundBadge: {
      width: 48,
      height: 36,
      borderRadius: 6,
      backgroundColor: Colors.surfaceLifted,
      borderColor: Colors.coltsNavyLight,
      borderWidth: 0.5,
      justifyContent: 'center',
      alignItems: 'center',
    },
    valueRoundText: {
      fontFamily: Fonts.stats,
      fontSize: 9,
      fontWeight: 'bold',
      color: Colors.secondaryAccent,
    },
    valuePickText: {
      fontFamily: Fonts.stats,
      fontSize: 7.5,
      color: Colors.secondaryAccent,
    },
    valueHeadshot: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: Colors.surfaceLifted,
    },
    valueInfo: {
      flex: 1,
      justifyContent: 'center',
    },
    valueName: {
      fontFamily: Fonts.body,
      fontSize: 12,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
    },
    valueMeta: {
      fontFamily: Fonts.body,
      fontSize: 9.5,
      color: Colors.secondaryAccent,
    },
    valBadge: {
      paddingVertical: 4,
      paddingHorizontal: 8,
      borderRadius: 4,
      minWidth: 64,
      alignItems: 'center',
      backgroundColor: Colors.surfaceLifted,
    },
    valSteal: {
      backgroundColor: '#dcfce7',
      borderColor: '#bbf7d0',
      borderWidth: 0.5,
    },
    valStealText: {
      color: '#15803d',
      fontWeight: 'bold',
    },
    valReach: {
      backgroundColor: '#fee2e2',
      borderColor: '#fecaca',
      borderWidth: 0.5,
    },
    valReachText: {
      color: '#b91c1c',
      fontWeight: 'bold',
    },
    valBadgeText: {
      fontFamily: Fonts.stats,
      fontSize: 8,
      fontWeight: 'bold',
      color: Colors.secondaryAccent,
    },

    // Performance Tab styles
    perfContainer: {
      gap: Spacing.three,
    },
    telemetryCard: {
      backgroundColor: Colors.surface,
      borderColor: Colors.coltsNavyLight,
      borderWidth: 1,
      borderRadius: 12,
      padding: Spacing.four,
      gap: Spacing.two,
      ...Colors.shadows,
    },
    telemetryCardTitle: {
      fontFamily: Fonts.headings,
      fontSize: 12,
      color: Colors.secondaryAccent,
      letterSpacing: 1,
    },
    telemetryStatsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 4,
    },
    telemetryStat: {
      flex: 1,
      backgroundColor: Colors.surfaceLifted,
      padding: 8,
      borderRadius: 8,
      alignItems: 'center',
      gap: 4,
    },
    telemetryStatLabel: {
      fontFamily: Fonts.stats,
      fontSize: 7,
      color: Colors.secondaryAccent,
      textAlign: 'center',
    },
    telemetryStatVal: {
      fontFamily: Fonts.stats,
      fontSize: 16,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
    },
    perfSectionTitle: {
      fontFamily: Fonts.stats,
      fontSize: 10,
      color: Colors.secondaryAccent,
      letterSpacing: 1.5,
      marginTop: Spacing.two,
    },
    routineGrid: {
      flexDirection: 'row',
      gap: Spacing.two,
    },
    routineCard: {
      flex: 1,
      backgroundColor: Colors.surface,
      borderWidth: 1,
      borderColor: Colors.coltsNavyLight,
      borderRadius: 12,
      padding: Spacing.three,
      gap: Spacing.one,
      ...Colors.shadows,
    },
    routineHeading: {
      fontFamily: Fonts.headings,
      fontSize: 11,
      color: Colors.primaryAccent,
      fontWeight: 'bold',
      marginBottom: 4,
    },
    routineBullet: {
      fontFamily: Fonts.body,
      fontSize: 11,
      color: Colors.secondaryAccent,
      lineHeight: 15,
    },
    weeklyList: {
      gap: 6,
    },
    weeklyRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.surface,
      borderColor: Colors.coltsNavyLight,
      borderWidth: 1,
      borderRadius: 8,
      paddingVertical: 6,
      paddingHorizontal: Spacing.two,
      gap: Spacing.two,
      height: 58,
    },
    weeklyRoundLabel: {
      width: 44,
      height: 32,
      borderRadius: 6,
      backgroundColor: Colors.surfaceLifted,
      justifyContent: 'center',
      alignItems: 'center',
    },
    weeklyRoundText: {
      fontFamily: Fonts.stats,
      fontSize: 9.5,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
    },
    weeklyRangeContainer: {
      flex: 1,
      justifyContent: 'center',
      gap: 2,
    },
    weeklyRangeLabelText: {
      fontFamily: Fonts.body,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#94a3b8',
    },
    rangeBarBg: {
      height: 6,
      backgroundColor: Colors.surfaceLifted,
      borderRadius: 3,
      position: 'relative',
      overflow: 'visible',
      width: '90%',
    },
    rangeBarFill: {
      height: 6,
      backgroundColor: 'rgba(224, 49, 34, 0.15)',
      borderRadius: 3,
      position: 'absolute',
    },
    rangeDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: Colors.coltsNavy,
      position: 'absolute',
      top: -1,
    },
    weeklyScoreDetail: {
      fontFamily: Fonts.stats,
      fontSize: 7.5,
      color: Colors.secondaryAccent,
    },
    matchOutcomeBadge: {
      paddingVertical: 4,
      paddingHorizontal: 8,
      borderRadius: 4,
      minWidth: 64,
      alignItems: 'center',
    },
    matchWin: {
      backgroundColor: '#dcfce7',
    },
    matchLoss: {
      backgroundColor: '#fee2e2',
    },
    matchWinText: {
      fontFamily: Fonts.stats,
      fontSize: 8.5,
      fontWeight: 'bold',
      color: '#15803d',
    },
    matchLossText: {
      fontFamily: Fonts.stats,
      fontSize: 8.5,
      fontWeight: 'bold',
      color: '#b91c1c',
    },
    matchOutcomeText: {
      fontFamily: Fonts.stats,
      fontSize: 8.5,
      fontWeight: 'bold',
    },
    quarterGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.two,
    },
    quarterCard: {
      width: '48%',
      backgroundColor: Colors.surface,
      borderColor: Colors.coltsNavyLight,
      borderWidth: 1,
      borderRadius: 12,
      padding: Spacing.three,
      gap: 3,
      ...Colors.shadows,
    },
    quarterTitle: {
      fontFamily: Fonts.headings,
      fontSize: 11,
      color: Colors.primaryAccent,
      fontWeight: 'bold',
    },
    quarterSubtitle: {
      fontFamily: Fonts.body,
      fontSize: 9,
      color: Colors.secondaryAccent,
      fontStyle: 'italic',
    },
    quarterStat: {
      fontFamily: Fonts.stats,
      fontSize: 8.5,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
      marginTop: 4,
    },
    quarterBody: {
      fontFamily: Fonts.body,
      fontSize: 10,
      color: Colors.secondaryAccent,
      lineHeight: 13,
      marginTop: 2,
    },

    // Leaderboard Lobby styles
    lobbyContainer: {
      gap: Spacing.three,
    },
    aiPanel: {
      backgroundColor: Colors.surface,
      borderColor: Colors.coltsNavyLight,
      borderWidth: 1,
      borderRadius: 12,
      padding: Spacing.four,
      gap: Spacing.two,
      ...Colors.shadows,
    },
    aiPanelTitle: {
      fontFamily: Fonts.headings,
      fontSize: 11,
      color: Colors.primaryAccent,
      letterSpacing: 1,
    },
    chartWrapper: {
      height: 100,
      alignItems: 'center',
      justifyContent: 'center',
      marginVertical: 4,
    },
    aiProgressMetaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    aiProgressLabel: {
      fontFamily: Fonts.stats,
      fontSize: 7.5,
      color: Colors.secondaryAccent,
      letterSpacing: 0.5,
    },
    aiProgressVal: {
      fontFamily: Fonts.stats,
      fontSize: 12,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
    },
    aiProgressBarBg: {
      height: 8,
      backgroundColor: Colors.surfaceLifted,
      borderRadius: 4,
      overflow: 'hidden',
      marginTop: 2,
    },
    aiProgressBarFill: {
      height: 8,
      backgroundColor: Colors.coltsNavy,
      borderRadius: 4,
    },
    aiProgressExplanation: {
      fontFamily: Fonts.body,
      fontSize: 11,
      color: Colors.secondaryAccent,
      lineHeight: 14,
      opacity: 0.8,
    },
    aiActionRow: {
      flexDirection: 'row',
      gap: Spacing.two,
      marginTop: Spacing.two,
    },
    aiActionBtn: {
      flex: 1.2,
      backgroundColor: Colors.coltsNavy,
      borderColor: Colors.coltsNavy,
      borderWidth: 1.5,
      borderRadius: 8,
      paddingVertical: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    aiActionBtnText: {
      fontFamily: Fonts.headings,
      fontSize: 11,
      color: '#FFFFFF',
      fontWeight: 'bold',
      letterSpacing: 0.5,
    },
    aiClearBtn: {
      flex: 0.8,
      borderColor: Colors.coltsNavyLight,
      borderWidth: 1,
      backgroundColor: 'transparent',
    },
    aiActionBtnTextClear: {
      fontFamily: Fonts.headings,
      fontSize: 11,
      color: '#ef4444',
      letterSpacing: 0.5,
    },
    lobbySectionTitle: {
      fontFamily: Fonts.stats,
      fontSize: 10,
      color: Colors.secondaryAccent,
      letterSpacing: 1.5,
      marginTop: Spacing.two,
    },
    tableContainer: {
      borderColor: Colors.coltsNavyLight,
      borderWidth: 1,
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: Colors.surface,
      width: 530,
    },
    tableHeaderRow: {
      flexDirection: 'row',
      backgroundColor: Colors.surfaceLifted,
      borderBottomWidth: 1,
      borderBottomColor: Colors.coltsNavyLight,
      paddingVertical: 8,
      paddingHorizontal: 8,
    },
    tableHeaderCell: {
      fontFamily: Fonts.stats,
      fontSize: 8.5,
      fontWeight: '800',
      color: Colors.secondaryAccent,
      letterSpacing: 1.5,
    },
    tableRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 0.5,
      borderBottomColor: Colors.coltsNavyLight,
      paddingVertical: 8,
      paddingHorizontal: 8,
    },
    tableRowHuman: {
      backgroundColor: 'rgba(255, 205, 0, 0.12)',
      borderBottomColor: 'rgba(255, 205, 0, 0.25)',
      borderBottomWidth: 1,
    },
    tableCellText: {
      fontFamily: Fonts.body,
      fontSize: 11,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
    },
    tableCellHumanText: {
      color: Colors.primaryAccent,
      fontWeight: 'bold',
    },
    tableNameCell: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    cpuSubLabel: {
      fontFamily: Fonts.stats,
      fontSize: 7.5,
      color: Colors.secondaryAccent,
    },
    tableCell: {
      fontFamily: Fonts.body,
      fontSize: 10.5,
      color: Colors.secondaryAccent,
    },
    greenProgressCircleBadge: {
      position: 'absolute',
      top: 8,
      right: 8,
      width: 52,
      height: 52,
      borderRadius: 26,
      borderWidth: 2,
      borderColor: '#22c55e',
      backgroundColor: '#f0fdf4',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#22c55e',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
      elevation: 3,
    },
    greenProgressCircleBadgeActive: {
      borderColor: '#4ade80',
      backgroundColor: '#dcfce7',
      shadowOpacity: 0.3,
      shadowRadius: 10,
    },
    greenProgressCircleBadgeText: {
      fontFamily: Fonts.stats,
      fontSize: 13,
      fontWeight: 'bold',
      color: '#15803d',
    },
    greenProgressCircleBadgeSubText: {
      fontFamily: Fonts.body,
      fontSize: 6.5,
      color: '#166534',
      fontWeight: 'bold',
      letterSpacing: 0.2,
      marginTop: -1,
    },
    exploreTooltip: {
      marginTop: Spacing.two,
      backgroundColor: Colors.surface,
      borderColor: Colors.coltsNavyLight,
      borderWidth: 1,
      borderRadius: 6,
      paddingVertical: 6,
      paddingHorizontal: 12,
      alignSelf: 'center',
      ...Colors.shadows,
    },
    exploreTooltipText: {
      fontFamily: Fonts.stats,
      fontSize: 9.5,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
      letterSpacing: 0.5,
    },

    // Bottom action buttons
    actionContainer: {
      gap: Spacing.two,
      marginTop: Spacing.two,
    },
    primaryBtn: {
      backgroundColor: Colors.coltsNavy,
      borderColor: Colors.coltsNavy,
      borderWidth: 1.5,
      borderRadius: 8,
      paddingVertical: 12,
      minHeight: 48,
      justifyContent: 'center',
      alignItems: 'center',
    },
    primaryBtnText: {
      fontFamily: Fonts.headings,
      fontSize: 14,
      color: '#FFFFFF',
      fontWeight: 'bold',
      letterSpacing: 1,
    },
    secondaryBtn: {
      backgroundColor: 'transparent',
      borderColor: Colors.primaryAccent,
      borderWidth: 1,
      borderRadius: 8,
      paddingVertical: 12,
      minHeight: 48,
      justifyContent: 'center',
      alignItems: 'center',
    },
    secondaryBtnText: {
      fontFamily: Fonts.headings,
      fontSize: 14,
      color: Colors.primaryAccent,
      fontWeight: 'bold',
      letterSpacing: 1,
    },
    btnPressed: {
      opacity: 0.85,
      transform: [{ scale: 0.98 }],
    },

    // Draft Board Styles
    boardSection: {
      padding: Spacing.three,
      backgroundColor: Colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: Colors.coltsNavyLight,
      marginHorizontal: Spacing.three,
      marginTop: Spacing.two,
      marginBottom: Spacing.four,
      overflow: 'hidden',
      ...Colors.shadows,
    },
    boardHeaderCard: {
      marginBottom: Spacing.three,
    },
    boardHeaderTitle: {
      fontFamily: Fonts.headings,
      fontSize: 20,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
      textTransform: 'uppercase',
    },
    boardHeaderSub: {
      fontFamily: Fonts.body,
      fontSize: 12,
      color: Colors.secondaryAccent,
      marginTop: Spacing.one,
      lineHeight: 16,
    },
    boardGridContainer: {
      flexDirection: 'column',
      alignItems: 'flex-start',
    },
    boardRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Spacing.half,
    },
    boardRoundHeaderCell: {
      width: 60,
      justifyContent: 'center',
      alignItems: 'center',
      paddingRight: Spacing.one,
    },
    boardRoundHeaderText: {
      fontFamily: Fonts.headings,
      fontSize: 11,
      fontWeight: 'bold',
      color: Colors.secondaryAccent,
      textAlign: 'center',
    },
    boardTeamHeaderCell: {
      width: 120,
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: Colors.surfaceLifted,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: Colors.coltsNavyLight,
      marginHorizontal: Spacing.half,
      paddingHorizontal: Spacing.one,
    },
    boardTeamHeaderCellUser: {
      borderColor: isDark ? Colors.secondaryAccent : Colors.coltsNavy,
      backgroundColor: 'rgba(224, 49, 34, 0.08)',
    },
    boardTeamHeaderText: {
      fontFamily: Fonts.headings,
      fontSize: 12,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
      textAlign: 'center',
    },
    boardTeamHeaderTextUser: {
      color: Colors.primaryAccent,
    },
    boardTeamSubText: {
      fontFamily: Fonts.stats,
      fontSize: 10,
      color: Colors.secondaryAccent,
      marginTop: Spacing.half,
    },
    boardRoundCell: {
      width: 60,
      justifyContent: 'center',
      alignItems: 'center',
      paddingRight: Spacing.one,
    },
    boardRoundCellText: {
      fontFamily: Fonts.stats,
      fontSize: 12,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
      textAlign: 'center',
    },
    boardPlayerCell: {
      width: 120,
      height: 64,
      backgroundColor: Colors.surfaceLifted,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: Colors.coltsNavyLight,
      marginHorizontal: Spacing.half,
      padding: Spacing.one,
      justifyContent: 'space-between',
    },
    boardPlayerCellUser: {
      borderColor: 'rgba(255, 205, 0, 0.5)',
      backgroundColor: 'rgba(255, 205, 0, 0.08)',
    },
    boardCellTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    boardCellPosBadge: {
      paddingHorizontal: Spacing.one,
      paddingVertical: 1,
      borderRadius: 4,
    },
    boardCellPosText: {
      fontFamily: Fonts.headings,
      fontSize: 10,
      fontWeight: 'bold',
      color: '#000000',
    },
    boardCellPickNumber: {
      fontFamily: Fonts.stats,
      fontSize: 9,
      color: '#64748b',
    },
    boardCellName: {
      fontFamily: Fonts.body,
      fontSize: 11,
      fontWeight: '600',
      color: Colors.primaryAccent,
      marginTop: 2,
    },
    boardCellMeta: {
      fontFamily: Fonts.body,
      fontSize: 9,
      color: Colors.secondaryAccent,
      marginTop: 1,
    },
    boardPlayerCellEmpty: {
      width: 120,
      height: 64,
      backgroundColor: 'transparent',
      borderRadius: 8,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: Colors.coltsNavyLight,
      marginHorizontal: Spacing.half,
      justifyContent: 'center',
      alignItems: 'center',
    },
    boardPlayerTextEmpty: {
      color: '#64748b',
      fontSize: 16,
    },
  });
}

const lightStyles = createStyles(LightColors);
const darkStyles = createStyles(DarkColors as any);

export const summaryStyles = new Proxy({}, {
  get(target, prop) {
    const theme = useThemeStore.getState().theme;
    return theme === 'dark' ? darkStyles[prop as keyof typeof darkStyles] : lightStyles[prop as keyof typeof lightStyles];
  }
}) as ReturnType<typeof createStyles>;
