import { StyleSheet, Platform } from 'react-native';
import { useThemeStore } from '@/store/useThemeStore';
import { Colors, Fonts, Spacing, MaxContentWidth, LightColors, DarkColors } from '@/constants/theme';

export function createStyles(Colors: typeof LightColors) {
  const isDark = (Colors.primaryAccent as string) === '#FFFFFF';
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors.primaryAccent,
    },
    safeArea: {
      flex: 1,
      alignSelf: 'center',
      width: '100%',
      maxWidth: MaxContentWidth,
    },
    scrollContent: {
      paddingHorizontal: Spacing.four,
      paddingTop: Spacing.two,
      paddingBottom: 120,
      gap: Spacing.four,
    },
    tabSwitcher: {
      flexDirection: 'row',
      backgroundColor: isDark ? Colors.obsidianBlack : '#E2E8F0',
      borderColor: Colors.midGray,
      borderWidth: 1.5,
      borderRadius: 10,
      padding: 4,
      minHeight: 46,
      marginHorizontal: Spacing.four,
    },
    tabButton: {
      flex: 1,
      height: 38,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
    },
    tabButtonActive: {
      backgroundColor: Colors.deepGraphiteCharcoal,
      borderColor: Colors.midGray,
      borderWidth: 1.5,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    tabButtonText: {
      fontFamily: Fonts.headings,
      fontSize: 12,
      color: isDark ? Colors.secondaryAccent : '#64748b',
      letterSpacing: 0.5,
    },
    tabButtonTextActive: {
      color: Colors.primaryAccent,
      fontWeight: 'bold',
    },
    simulatingOverlay: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: isDark ? 'rgba(12, 12, 12, 0.95)' : 'rgba(248, 250, 252, 0.95)',
      zIndex: 999,
      justifyContent: 'center',
      alignItems: 'center',
      gap: Spacing.three,
    },
    simulatingText: {
      fontFamily: Fonts.headings,
      fontSize: 15,
      color: Colors.primaryAccent,
      letterSpacing: 0.5,
    },
    overlayProgressBarBg: {
      width: 240,
      height: 8,
      backgroundColor: Colors.liftedCharcoal,
      borderRadius: 4,
      overflow: 'hidden',
      marginTop: Spacing.one,
      borderColor: Colors.midGray,
      borderWidth: 1.5,
    },
    overlayProgressBarFill: {
      height: '100%',
      backgroundColor: Colors.deepFieldGreen,
      borderRadius: 4,
    },

    // Coach Feedback styles
    coachContainer: {
      gap: Spacing.three,
    },
    coachBubble: {
      backgroundColor: Colors.deepGraphiteCharcoal,
      borderColor: Colors.pigskinBrown,
      borderWidth: 1.5,
      borderRadius: 12,
      padding: Spacing.four,
      gap: Spacing.two,
      ...Colors.shadows,
    },
    coachTitle: {
      fontFamily: Fonts.headings,
      fontSize: 14,
      color: Colors.secondaryAccent,
      letterSpacing: 0.5,
    },
    coachStatus: {
      fontFamily: Fonts.stats,
      fontSize: 10,
      fontWeight: 'bold',
      letterSpacing: 1.5,
    },
    coachSuccess: {
      color: '#22c55e',
    },
    coachWarning: {
      color: '#eab308',
    },
    coachFeedback: {
      fontFamily: Fonts.body,
      fontSize: 13,
      color: Colors.primaryAccent,
      lineHeight: 18,
      opacity: 0.9,
    },
    coachSubHeader: {
      fontFamily: Fonts.stats,
      fontSize: 9,
      fontWeight: 'bold',
      color: Colors.secondaryAccent,
      letterSpacing: 1,
      marginTop: Spacing.two,
    },
    coachSuggestionItem: {
      fontFamily: Fonts.body,
      fontSize: 12,
      color: Colors.secondaryAccent,
      lineHeight: 16,
    },
    coachSectionTitle: {
      fontFamily: Fonts.stats,
      fontSize: 10,
      color: Colors.secondaryAccent,
      letterSpacing: 1.5,
      marginTop: Spacing.two,
    },
    valueList: {
      gap: 6,
    },
    valueRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.deepGraphiteCharcoal,
      borderColor: Colors.pigskinBrown,
      borderWidth: 1.5,
      borderRadius: 8,
      paddingVertical: 6,
      paddingHorizontal: Spacing.two,
      gap: Spacing.two,
      height: 58,
    },
    valueRoundBadge: {
      width: 48,
      height: 36,
      borderRadius: 6,
      backgroundColor: Colors.liftedCharcoal,
      borderColor: Colors.chromeSilver,
      borderWidth: 0.5,
      justifyContent: 'center',
      alignItems: 'center',
    },
    valueRoundText: {
      fontFamily: Fonts.stats,
      fontSize: 9,
      fontWeight: 'bold',
      color: Colors.secondaryAccent,
    },
    valuePickText: {
      fontFamily: Fonts.stats,
      fontSize: 7.5,
      color: Colors.secondaryAccent,
    },
    valueHeadshot: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: Colors.liftedCharcoal,
    },
    valueInfo: {
      flex: 1,
      justifyContent: 'center',
    },
    valueName: {
      fontFamily: Fonts.body,
      fontSize: 12,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
    },
    valueMeta: {
      fontFamily: Fonts.body,
      fontSize: 9.5,
      color: Colors.secondaryAccent,
    },
    valBadge: {
      paddingVertical: 4,
      paddingHorizontal: 8,
      borderRadius: 4,
      minWidth: 64,
      alignItems: 'center',
      backgroundColor: Colors.liftedCharcoal,
    },
    valSteal: {
      backgroundColor: '#dcfce7',
      borderColor: '#bbf7d0',
      borderWidth: 1.5,
    },
    valStealText: {
      color: '#15803d',
      fontWeight: 'bold',
    },
    valReach: {
      backgroundColor: '#fee2e2',
      borderColor: '#fecaca',
      borderWidth: 1.5,
    },
    valReachText: {
      color: '#b91c1c',
      fontWeight: 'bold',
    },
    valBadgeText: {
      fontFamily: Fonts.stats,
      fontSize: 8,
      fontWeight: 'bold',
      color: Colors.secondaryAccent,
    },

    // Performance Tab styles
    perfContainer: {
      gap: Spacing.three,
    },
    telemetryCard: {
      backgroundColor: Colors.deepGraphiteCharcoal,
      borderColor: Colors.pigskinBrown,
      borderWidth: 1.5,
      borderRadius: 12,
      padding: Spacing.four,
      gap: Spacing.two,
      ...Colors.shadows,
    },
    telemetryCardTitle: {
      fontFamily: Fonts.headings,
      fontSize: 12,
      color: Colors.secondaryAccent,
      letterSpacing: 1,
    },
    telemetryStatsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 4,
    },
    telemetryStat: {
      flex: 1,
      backgroundColor: Colors.liftedCharcoal,
      padding: 8,
      borderRadius: 8,
      alignItems: 'center',
      gap: 4,
    },
    telemetryStatLabel: {
      fontFamily: Fonts.stats,
      fontSize: 7,
      color: Colors.secondaryAccent,
      textAlign: 'center',
    },
    telemetryStatVal: {
      fontFamily: Fonts.stats,
      fontSize: 16,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
    },
    perfSectionTitle: {
      fontFamily: Fonts.stats,
      fontSize: 10,
      color: Colors.secondaryAccent,
      letterSpacing: 1.5,
      marginTop: Spacing.two,
    },
    routineGrid: {
      flexDirection: 'row',
      gap: Spacing.two,
    },
    routineCard: {
      flex: 1,
      backgroundColor: Colors.deepGraphiteCharcoal,
      borderWidth: 1.5,
      borderColor: Colors.pigskinBrown,
      borderRadius: 12,
      padding: Spacing.three,
      gap: Spacing.one,
      ...Colors.shadows,
    },
    routineHeading: {
      fontFamily: Fonts.headings,
      fontSize: 11,
      color: Colors.primaryAccent,
      fontWeight: 'bold',
      marginBottom: 4,
    },
    routineBullet: {
      fontFamily: Fonts.body,
      fontSize: 11,
      color: Colors.secondaryAccent,
      lineHeight: 15,
    },
    weeklyList: {
      gap: 6,
    },
    weeklyRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.deepGraphiteCharcoal,
      borderColor: Colors.pigskinBrown,
      borderWidth: 1.5,
      borderRadius: 8,
      paddingVertical: 6,
      paddingHorizontal: Spacing.two,
      gap: Spacing.two,
      height: 58,
    },
    weeklyRoundLabel: {
      width: 44,
      height: 32,
      borderRadius: 6,
      backgroundColor: Colors.liftedCharcoal,
      justifyContent: 'center',
      alignItems: 'center',
    },
    weeklyRoundText: {
      fontFamily: Fonts.stats,
      fontSize: 9.5,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
    },
    weeklyRangeContainer: {
      flex: 1,
      justifyContent: 'center',
      gap: 2,
    },
    weeklyRangeLabelText: {
      fontFamily: Fonts.body,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#94a3b8',
    },
    rangeBarBg: {
      height: 6,
      backgroundColor: Colors.liftedCharcoal,
      borderRadius: 3,
      position: 'relative',
      overflow: 'visible',
      width: '90%',
    },
    rangeBarFill: {
      height: 6,
      backgroundColor: 'rgba(224, 49, 34, 0.15)',
      borderRadius: 3,
      position: 'absolute',
    },
    rangeDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: Colors.deepFieldGreen,
      position: 'absolute',
      top: -1,
    },
    weeklyScoreDetail: {
      fontFamily: Fonts.stats,
      fontSize: 7.5,
      color: Colors.secondaryAccent,
    },
    matchOutcomeBadge: {
      paddingVertical: 4,
      paddingHorizontal: 8,
      borderRadius: 4,
      minWidth: 64,
      alignItems: 'center',
    },
    matchWin: {
      backgroundColor: '#dcfce7',
    },
    matchLoss: {
      backgroundColor: '#fee2e2',
    },
    matchWinText: {
      fontFamily: Fonts.stats,
      fontSize: 8.5,
      fontWeight: 'bold',
      color: '#15803d',
    },
    matchLossText: {
      fontFamily: Fonts.stats,
      fontSize: 8.5,
      fontWeight: 'bold',
      color: '#b91c1c',
    },
    matchOutcomeText: {
      fontFamily: Fonts.stats,
      fontSize: 8.5,
      fontWeight: 'bold',
    },
    quarterGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.two,
    },
    quarterCard: {
      width: '48%',
      backgroundColor: Colors.deepGraphiteCharcoal,
      borderColor: Colors.pigskinBrown,
      borderWidth: 1.5,
      borderRadius: 12,
      padding: Spacing.three,
      gap: 3,
      ...Colors.shadows,
    },
    quarterTitle: {
      fontFamily: Fonts.headings,
      fontSize: 11,
      color: Colors.primaryAccent,
      fontWeight: 'bold',
    },
    quarterSubtitle: {
      fontFamily: Fonts.body,
      fontSize: 9,
      color: Colors.secondaryAccent,
      fontStyle: 'italic',
    },
    quarterStat: {
      fontFamily: Fonts.stats,
      fontSize: 8.5,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
      marginTop: 4,
    },
    quarterBody: {
      fontFamily: Fonts.body,
      fontSize: 10,
      color: Colors.secondaryAccent,
      lineHeight: 13,
      marginTop: 2,
    },

    // Leaderboard Lobby styles
    lobbyContainer: {
      gap: Spacing.three,
    },
    aiPanel: {
      backgroundColor: Colors.deepGraphiteCharcoal,
      borderColor: Colors.pigskinBrown,
      borderWidth: 1.5,
      borderRadius: 12,
      padding: Spacing.four,
      gap: Spacing.two,
      ...Colors.shadows,
    },
    aiPanelTitle: {
      fontFamily: Fonts.headings,
      fontSize: 11,
      color: Colors.primaryAccent,
      letterSpacing: 1,
    },
    chartWrapper: {
      height: 100,
      alignItems: 'center',
      justifyContent: 'center',
      marginVertical: 4,
    },
    aiProgressMetaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    aiProgressLabel: {
      fontFamily: Fonts.stats,
      fontSize: 7.5,
      color: Colors.secondaryAccent,
      letterSpacing: 0.5,
    },
    aiProgressVal: {
      fontFamily: Fonts.stats,
      fontSize: 12,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
    },
    aiProgressBarBg: {
      height: 8,
      backgroundColor: Colors.liftedCharcoal,
      borderRadius: 4,
      overflow: 'hidden',
      marginTop: 2,
    },
    aiProgressBarFill: {
      height: 8,
      backgroundColor: Colors.deepFieldGreen,
      borderRadius: 4,
    },
    aiProgressExplanation: {
      fontFamily: Fonts.body,
      fontSize: 11,
      color: Colors.secondaryAccent,
      lineHeight: 14,
      opacity: 0.8,
    },
    aiActionRow: {
      flexDirection: 'row',
      gap: Spacing.two,
      marginTop: Spacing.two,
    },
    aiActionBtn: {
      flex: 1.2,
      backgroundColor: Colors.pylonOrange,
      borderColor: Colors.pylonOrange,
      borderWidth: 1.5,
      borderRadius: 8,
      paddingVertical: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    aiActionBtnText: {
      fontFamily: Fonts.headings,
      fontSize: 11,
      color: '#FFFFFF',
      fontWeight: 'bold',
      letterSpacing: 0.5,
    },
    aiClearBtn: {
      flex: 0.8,
      borderColor: Colors.midGray,
      borderWidth: 1.5,
      backgroundColor: 'transparent',
    },
    aiActionBtnTextClear: {
      fontFamily: Fonts.headings,
      fontSize: 11,
      color: '#ef4444',
      letterSpacing: 0.5,
    },
    lobbySectionTitle: {
      fontFamily: Fonts.stats,
      fontSize: 10,
      color: Colors.secondaryAccent,
      letterSpacing: 1.5,
      marginTop: Spacing.two,
    },
    tableContainer: {
      borderColor: Colors.pigskinBrown,
      borderWidth: 1.5,
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: Colors.deepGraphiteCharcoal,
      width: 530,
    },
    tableHeaderRow: {
      flexDirection: 'row',
      backgroundColor: Colors.liftedCharcoal,
      borderBottomWidth: 1,
      borderBottomColor: Colors.chromeSilver,
      paddingVertical: 8,
      paddingHorizontal: 8,
    },
    tableHeaderCell: {
      fontFamily: Fonts.stats,
      fontSize: 8.5,
      fontWeight: '800',
      color: Colors.secondaryAccent,
      letterSpacing: 1.5,
    },
    tableRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 0.5,
      borderBottomColor: Colors.chromeSilver,
      paddingVertical: 8,
      paddingHorizontal: 8,
    },
    tableRowHuman: {
      backgroundColor: 'rgba(255, 205, 0, 0.12)',
      borderBottomColor: 'rgba(255, 205, 0, 0.25)',
      borderBottomWidth: 1,
    },
    tableCellText: {
      fontFamily: Fonts.body,
      fontSize: 11,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
    },
    tableCellHumanText: {
      color: Colors.primaryAccent,
      fontWeight: 'bold',
    },
    tableNameCell: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    cpuSubLabel: {
      fontFamily: Fonts.stats,
      fontSize: 7.5,
      color: Colors.secondaryAccent,
    },
    tableCell: {
      fontFamily: Fonts.body,
      fontSize: 10.5,
      color: Colors.secondaryAccent,
    },
    greenProgressCircleBadge: {
      position: 'absolute',
      top: 8,
      right: 8,
      width: 52,
      height: 52,
      borderRadius: 26,
      borderWidth: 2,
      borderColor: '#22c55e',
      backgroundColor: '#f0fdf4',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#22c55e',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
      elevation: 3,
    },
    greenProgressCircleBadgeActive: {
      borderColor: '#4ade80',
      backgroundColor: '#dcfce7',
      shadowOpacity: 0.3,
      shadowRadius: 10,
    },
    greenProgressCircleBadgeText: {
      fontFamily: Fonts.stats,
      fontSize: 13,
      fontWeight: 'bold',
      color: '#15803d',
    },
    greenProgressCircleBadgeSubText: {
      fontFamily: Fonts.body,
      fontSize: 6.5,
      color: '#166534',
      fontWeight: 'bold',
      letterSpacing: 0.2,
      marginTop: -1,
    },
    exploreTooltip: {
      marginTop: Spacing.two,
      backgroundColor: Colors.deepGraphiteCharcoal,
      borderColor: Colors.pigskinBrown,
      borderWidth: 1.5,
      borderRadius: 6,
      paddingVertical: 6,
      paddingHorizontal: 12,
      alignSelf: 'center',
      ...Colors.shadows,
    },
    exploreTooltipText: {
      fontFamily: Fonts.stats,
      fontSize: 9.5,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
      letterSpacing: 0.5,
    },

    // Draft Board Styles
    boardSection: {
      padding: Spacing.three,
      backgroundColor: Colors.deepGraphiteCharcoal,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: Colors.pigskinBrown,
      marginHorizontal: Spacing.three,
      marginTop: Spacing.two,
      marginBottom: Spacing.four,
      overflow: 'hidden',
      ...Colors.shadows,
    },
    boardHeaderCard: {
      marginBottom: Spacing.three,
    },
    boardHeaderTitle: {
      fontFamily: Fonts.headings,
      fontSize: 20,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
      textTransform: 'uppercase',
    },
    boardHeaderSub: {
      fontFamily: Fonts.body,
      fontSize: 12,
      color: Colors.secondaryAccent,
      marginTop: Spacing.one,
      lineHeight: 16,
    },
    boardGridContainer: {
      flexDirection: 'column',
      alignItems: 'flex-start',
    },
    boardRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Spacing.half,
    },
    boardRoundHeaderCell: {
      width: 60,
      justifyContent: 'center',
      alignItems: 'center',
      paddingRight: Spacing.one,
    },
    boardRoundHeaderText: {
      fontFamily: Fonts.headings,
      fontSize: 11,
      fontWeight: 'bold',
      color: Colors.secondaryAccent,
      textAlign: 'center',
    },
    boardTeamHeaderCell: {
      width: 120,
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: Colors.liftedCharcoal,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: Colors.chromeSilver,
      marginHorizontal: Spacing.half,
      paddingHorizontal: Spacing.one,
    },
    boardTeamHeaderCellUser: {
      borderColor: isDark ? Colors.secondaryAccent : Colors.deepFieldGreen,
      backgroundColor: 'rgba(224, 49, 34, 0.08)',
    },
    boardTeamHeaderText: {
      fontFamily: Fonts.headings,
      fontSize: 12,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
      textAlign: 'center',
    },
    boardTeamHeaderTextUser: {
      color: Colors.primaryAccent,
    },
    boardTeamSubText: {
      fontFamily: Fonts.stats,
      fontSize: 10,
      color: Colors.secondaryAccent,
      marginTop: Spacing.half,
    },
    boardRoundCell: {
      width: 60,
      justifyContent: 'center',
      alignItems: 'center',
      paddingRight: Spacing.one,
    },
    boardRoundCellText: {
      fontFamily: Fonts.stats,
      fontSize: 12,
      fontWeight: 'bold',
      color: Colors.primaryAccent,
      textAlign: 'center',
    },
    boardPlayerCell: {
      width: 120,
      height: 64,
      backgroundColor: Colors.liftedCharcoal,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: Colors.chromeSilver,
      marginHorizontal: Spacing.half,
      padding: Spacing.one,
      justifyContent: 'space-between',
    },
    boardPlayerCellUser: {
      borderColor: 'rgba(255, 205, 0, 0.5)',
      backgroundColor: 'rgba(255, 205, 0, 0.08)',
    },
    boardCellTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    boardCellPosBadge: {
      paddingHorizontal: Spacing.one,
      paddingVertical: 1,
      borderRadius: 4,
    },
    boardCellPosText: {
      fontFamily: Fonts.headings,
      fontSize: 10,
      fontWeight: 'bold',
      color: '#000000',
    },
    boardCellPickNumber: {
      fontFamily: Fonts.stats,
      fontSize: 9,
      color: '#64748b',
    },
    boardCellName: {
      fontFamily: Fonts.body,
      fontSize: 11,
      fontWeight: '600',
      color: Colors.primaryAccent,
      marginTop: 2,
    },
    boardCellMeta: {
      fontFamily: Fonts.body,
      fontSize: 9,
      color: Colors.secondaryAccent,
      marginTop: 1,
    },
    boardPlayerCellEmpty: {
      width: 120,
      height: 64,
      backgroundColor: 'transparent',
      borderRadius: 8,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: Colors.chromeSilver,
      marginHorizontal: Spacing.half,
      justifyContent: 'center',
      alignItems: 'center',
    },
    boardPlayerTextEmpty: {
      color: '#64748b',
      fontSize: 16,
    },
    
    // PSA slab styles copied from recap.tsx for 100% exact look and feel
    cardContainer: {
      width: 280,
      height: 500,
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderRadius: 24,
      borderWidth: 9.5,
      borderColor: 'rgba(241, 245, 249, 0.48)',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.28,
      shadowRadius: 10,
      elevation: 7,
      overflow: 'hidden',
      alignSelf: 'center',
      marginBottom: Spacing.two,
    },
    maximizedCardFront: {
      flex: 1,
      width: '100%',
      height: '100%',
    },
    maximizedCardBack: {
      flex: 1,
      width: '100%',
      height: '100%',
      backgroundColor: '#1A1D21', // Deep Graphite
    },
    slabGlossOverlay: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 200,
      borderRadius: 14,
      overflow: 'hidden',
    },
    cardPressableArea: {
      flex: 1,
      width: '100%',
      padding: 10,
      borderWidth: 1.5,
      borderColor: 'rgba(255, 255, 255, 0.12)',
      borderRadius: 16,
    },
    cardPressableAreaPressed: {
      opacity: 0.95,
    },
    psaLabelContainer: {
      backgroundColor: '#FFFFFF',
      borderWidth: 3.5,
      borderColor: '#D9261C', // Branded PSA Red
      borderRadius: 8,
      padding: 5.5,
      marginBottom: 6,
    },
    psaTwoColumnLayout: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      backgroundColor: '#FFFFFF',
    },
    psaLeftColumn: {
      flex: 1.1,
      justifyContent: 'space-between',
      paddingRight: 6,
    },
    psaRightColumn: {
      width: 70,
      gap: 3.2,
      alignItems: 'stretch',
    },
    psaYearTag: {
      fontFamily: Fonts.stats,
      fontSize: 6.9,
      fontWeight: 'bold',
      color: '#64748b',
      letterSpacing: 0.28,
    },
    psaPlayerName: {
      fontFamily: Fonts.headings,
      fontSize: 12.5,
      fontWeight: '900',
      color: '#0c0c0c',
      marginVertical: 0.9,
    },
    psaMetaRow: {
      fontFamily: Fonts.stats,
      fontSize: 7.4,
      fontWeight: 'bold',
      color: '#475569',
    },
    psaStatRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      borderTopWidth: 0.5,
      borderColor: '#cbd5e1',
      paddingTop: 1.8,
      marginTop: 2.7,
    },
    psaStatCell: {
      alignItems: 'center',
      flex: 1,
    },
    psaStatLabel: {
      fontFamily: Fonts.body,
      fontSize: 6,
      color: '#64748b',
      fontWeight: 'bold',
    },
    psaStatValue: {
      fontFamily: Fonts.stats,
      fontSize: 8.3,
      fontWeight: '900',
      color: '#0c0c0c',
    },
    // Right Column Stack Styles
    psaEcrBox: {
      borderWidth: 0.5,
      borderColor: '#cbd5e1',
      borderRadius: 3.5,
      paddingVertical: 1.3,
      alignItems: 'center',
      backgroundColor: '#FAFAFA',
    },
    psaRightLabel: {
      fontFamily: Fonts.body,
      fontSize: 6,
      color: '#64748b',
      fontWeight: 'bold',
    },
    psaRightValue: {
      fontFamily: Fonts.stats,
      fontSize: 8.3,
      fontWeight: 'bold',
      color: '#0c0c0c',
    },
    psaAdpBox: {
      borderWidth: 1.1,
      borderColor: '#0c0c0c',
      borderRadius: 3.5,
      paddingVertical: 1.8,
      alignItems: 'center',
      backgroundColor: '#FFCD00', // Highlight Yellow!
    },
    psaAdpLabel: {
      fontFamily: Fonts.body,
      fontSize: 6.5,
      color: '#0c0c0c',
      fontWeight: '900',
    },
    psaAdpValue: {
      fontFamily: Fonts.stats,
      fontSize: 11,
      fontWeight: '900',
      color: '#0c0c0c',
    },
    psaGradeBox: {
      borderWidth: 0.5,
      borderColor: '#cbd5e1',
      borderRadius: 3.5,
      paddingVertical: 1.3,
      alignItems: 'center',
      backgroundColor: '#FAFAFA',
    },
    psaGradeLabel: {
      fontFamily: Fonts.body,
      fontSize: 5.5,
      color: '#D9261C', // Red description text
      fontWeight: '900',
    },
    psaGradeValue: {
      fontFamily: Fonts.headings,
      fontSize: 9.2,
      fontWeight: '900',
      color: '#D9261C',
    },
    chromeCardContainer: {
      flex: 1,
      borderWidth: 2,
      borderRadius: 10,
      overflow: 'hidden',
      position: 'relative',
      backgroundColor: '#1E293B',
    },
    chromeLightBeam: {
      position: 'absolute',
      top: -150,
      left: -75,
      width: 225,
      height: 600,
      backgroundColor: 'rgba(255, 255, 255, 0.12)',
      transform: [{ rotate: '25deg' }],
    },
    verticalTeamContainer: {
      position: 'absolute',
      left: 8,
      top: 30,
      bottom: 30,
      justifyContent: 'center',
      zIndex: 5,
    },
    verticalTeamText: {
      fontFamily: Fonts.headings,
      fontSize: 22,
      fontWeight: '900',
      opacity: 0.2,
      textAlign: 'center',
      lineHeight: 24,
    },
    rookieBadgeContainer: {
      position: 'absolute',
      top: 8,
      left: 8,
      zIndex: 10,
    },
    rookieBadgeTextWrapper: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'center',
    },
    rookieBadgeText: {
      fontFamily: Fonts.headings,
      fontSize: 11,
      fontWeight: 'bold',
      color: '#0c0c0c',
    },
    toppsChromeLogoContainer: {
      position: 'absolute',
      top: 8,
      right: 8,
      zIndex: 10,
      alignItems: 'flex-end',
    },
    toppsChromeLogoText: {
      fontFamily: 'Inter',
      fontSize: 9,
      fontStyle: 'italic',
      fontWeight: 'bold',
      color: '#FFFFFF',
    },
    toppsChromeSubText: {
      fontFamily: Fonts.headings,
      fontSize: 8.5,
      fontWeight: '900',
      color: '#FFCD00',
      letterSpacing: 0.2,
    },
    chromePlayerFrame: {
      width: '72%',
      height: '68%',
      alignSelf: 'center',
      marginTop: 26,
      borderWidth: 1.5,
      borderRadius: 100,
      overflow: 'hidden',
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    chromePlayerImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'contain',
    },
    autographContainer: {
      position: 'absolute',
      bottom: 36,
      left: 0,
      right: 0,
      alignItems: 'center',
      zIndex: 12,
    },
    autographText: {
      fontFamily: Platform.OS === 'ios' ? 'Snell Roundhand' : Platform.OS === 'web' ? 'Caveat' : 'cursive',
      fontSize: Platform.OS === 'ios' ? 32 : 26,
      fontWeight: 'bold',
      color: '#ffffff',
      letterSpacing: 0.5,
      transform: [{ rotate: '-8deg' }],
      opacity: 0.85,
    },
    autographSubText: {
      fontFamily: Fonts.body,
      fontSize: 6.5,
      color: 'rgba(255, 255, 255, 0.4)',
      letterSpacing: 0.5,
      marginTop: 3,
    },
    foilStampContainer: {
      position: 'absolute',
      bottom: 36,
      right: 15,
      zIndex: 10,
    },
    foilStampText: {
      fontFamily: Fonts.stats,
      fontSize: 10,
      color: '#FFD700',
      fontWeight: 'bold',
      opacity: 0.8,
    },
    chromePlayerBottomBar: {
      position: 'absolute',
      bottom: 6,
      left: 10,
      right: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      zIndex: 15,
      borderTopWidth: 0.5,
      borderColor: 'rgba(255,255,255,0.15)',
      paddingTop: 4,
    },
    chromeBottomLeftNameContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    chromeTeamMonogram: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    chromeTeamMonogramText: {
      fontFamily: Fonts.headings,
      fontSize: 12,
      fontWeight: '900',
      color: '#FFFFFF',
      fontStyle: 'italic',
      textTransform: 'uppercase',
    },
    chromeNameTextWrapper: {
      justifyContent: 'center',
    },
    chromePlayerFirstName: {
      fontFamily: Fonts.body,
      fontSize: 8.5,
      fontWeight: 'bold',
      color: '#cbd5e1',
      letterSpacing: 0.5,
      lineHeight: 9,
    },
    chromePlayerLastName: {
      fontFamily: Fonts.headings,
      fontSize: 15,
      fontWeight: '900',
      color: '#FFFFFF',
      marginTop: -2,
    },
    chromePosBox: {
      backgroundColor: 'rgba(255, 255, 255, 0.08)',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 4,
    },
    chromePosText: {
      fontFamily: Fonts.stats,
      fontSize: 9,
      color: '#cbd5e1',
    },
    expandedBackContainer: {
      flex: 1,
      padding: 12,
      justifyContent: 'space-between',
      backgroundColor: '#1A1D21',
    },
    expandedPsaHeader: {
      backgroundColor: '#FFFFFF',
      borderWidth: 3.5,
      borderColor: '#D9261C',
      borderRadius: 8,
      padding: 6,
      marginBottom: 10,
    },
    expandedPsaHeaderContent: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      backgroundColor: '#FFFFFF',
    },
    expandedPsaHeaderLeft: {
      flex: 1,
      justifyContent: 'center',
    },
    expandedPsaHeaderRight: {
      alignItems: 'flex-end',
      justifyContent: 'center',
      minWidth: 75,
    },
    expandedPsaHeaderKicker: {
      fontFamily: Fonts.stats,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#0c0c0c',
    },
    expandedPsaHeaderTitle: {
      fontFamily: Fonts.headings,
      fontSize: 13,
      fontWeight: '900',
      color: '#0c0c0c',
      marginTop: 2,
    },
    expandedPsaHeaderMeta: {
      fontFamily: Fonts.stats,
      fontSize: 9,
      color: '#475569',
      marginTop: 2,
    },
    expandedPsaHeaderGradeDesc: {
      fontFamily: Fonts.headings,
      fontSize: 10,
      fontWeight: 'bold',
      color: '#0c0c0c',
    },
    expandedPsaHeaderGradeNum: {
      fontFamily: Fonts.headings,
      fontSize: 22,
      fontWeight: '900',
      color: '#D9261C',
      marginTop: -3,
    },
    expandedPsaBarcodeRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderTopWidth: 0.5,
      borderColor: 'rgba(0,0,0,0.1)',
      paddingTop: 3,
      marginTop: 3,
    },
    expandedPsaBarcode: {
      fontFamily: Fonts.stats,
      fontSize: 8.5,
      letterSpacing: 0.2,
      color: '#0c0c0c',
    },
    expandedPsaSerial: {
      fontFamily: Fonts.stats,
      fontSize: 8.5,
      color: '#475569',
    },
    expandedScrollArea: {
      flex: 1,
      marginVertical: 4,
    },
    expandedSection: {
      marginBottom: 14,
    },
    expandedSectionTitle: {
      fontFamily: Fonts.headings,
      fontSize: 8.5,
      color: Colors.pigskinBrown,
      letterSpacing: 1.5,
      fontWeight: 'bold',
      marginBottom: 6,
    },
    rosterListContainer: {
      gap: 5,
    },
    rosterRowItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: 'rgba(255, 255, 255, 0.04)',
      paddingHorizontal: 8,
      paddingVertical: 6,
      borderRadius: 8,
      borderWidth: 0.5,
      borderColor: 'rgba(255, 255, 255, 0.05)',
    },
    rosterRowLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
    },
    rosterRoundPill: {
      backgroundColor: Colors.hofYellow,
      paddingHorizontal: 5,
      paddingVertical: 2,
      borderRadius: 4,
      minWidth: 34,
      alignItems: 'center',
    },
    rosterRoundText: {
      fontFamily: Fonts.stats,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#0c0c0c',
    },
    rosterPlayerInfo: {
      flex: 1,
      justifyContent: 'center',
    },
    rosterPlayerName: {
      fontFamily: Fonts.body,
      fontSize: 11,
      fontWeight: 'bold',
      color: '#FFFFFF',
    },
    rosterPlayerTeamPos: {
      fontFamily: Fonts.body,
      fontSize: 8.5,
      color: 'rgba(255, 255, 255, 0.5)',
      marginTop: 1,
    },
    rosterRowRight: {
      alignItems: 'flex-end',
    },
    rosterPickText: {
      fontFamily: Fonts.stats,
      fontSize: 10,
      color: Colors.hofYellow,
      fontWeight: 'bold',
    },
    expandedInsightsCard: {
      backgroundColor: 'rgba(255, 255, 255, 0.03)',
      borderRadius: 10,
      padding: 10,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.05)',
    },
    expandedInsightsText: {
      fontFamily: Fonts.body,
      fontSize: 10.5,
      color: '#e2e8f0',
      lineHeight: 15,
    },
    expandedTelemetryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 8,
    },
    expandedTelemetryBox: {
      flex: 1,
      backgroundColor: 'rgba(255, 255, 255, 0.03)',
      borderRadius: 8,
      padding: 8,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.05)',
    },
    expandedTelemetryVal: {
      fontFamily: Fonts.stats,
      fontSize: 13,
      fontWeight: 'bold',
      color: '#FFFFFF',
    },
    expandedTelemetryLbl: {
      fontFamily: Fonts.body,
      fontSize: 7.5,
      color: 'rgba(255, 255, 255, 0.5)',
      marginTop: 2,
    },
    expandedCloseFlipBtn: {
      backgroundColor: Colors.liftedCharcoal,
      borderWidth: 1,
      borderColor: Colors.chromeSilver,
      borderRadius: 10,
      paddingVertical: 8,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 4,
    },
    expandedCloseFlipBtnPressed: {
      opacity: 0.75,
    },
    expandedCloseFlipBtnText: {
      fontFamily: Fonts.body,
      fontSize: 10,
      fontWeight: 'bold',
      color: '#FFFFFF',
    },
    // RPA TEMPLATE STYLES
    rpaSerialContainer: {
      position: 'absolute',
      top: 8,
      right: 10,
      zIndex: 10,
      backgroundColor: '#FFFBEB',
      borderColor: '#F59E0B',
      borderWidth: 1,
      paddingHorizontal: 5,
      paddingVertical: 1,
      borderRadius: 4,
    },
    rpaSerialText: {
      fontFamily: Fonts.stats,
      fontSize: 8.5,
      color: '#B45309',
      fontWeight: 'bold',
    },
    rpaHeaderBrand: {
      position: 'absolute',
      top: 8,
      alignSelf: 'center',
      zIndex: 10,
    },
    rpaBrandName: {
      fontFamily: Fonts.headings,
      fontSize: 9,
      color: '#64748b',
      letterSpacing: 2,
      fontWeight: '900',
    },
    rpaPlayerFrame: {
      width: 135,
      height: 160,
      position: 'absolute',
      right: 12,
      top: 65,
      borderRadius: 8,
      borderWidth: 1,
      overflow: 'hidden',
    },
    rpaPlayerImage: {
      width: '100%',
      height: '100%',
    },
    jerseyPatchWindow: {
      width: 90,
      height: 90,
      position: 'absolute',
      left: 20,
      top: 85,
      borderRadius: 8,
      borderWidth: 1.5,
      borderColor: '#94A3B8',
      overflow: 'hidden',
      backgroundColor: '#1E293B',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    rpaAutographContainer: {
      position: 'absolute',
      bottom: 50,
      left: 0,
      right: 0,
      alignItems: 'center',
      zIndex: 12,
    },
    rpaAutographText: {
      fontFamily: Platform.OS === 'ios' ? 'Snell Roundhand' : Platform.OS === 'web' ? 'Caveat' : 'cursive',
      fontSize: 25,
      fontWeight: 'bold',
      color: '#1D4ED8',
      transform: [{ rotate: '-4deg' }],
    },

    // KABOOM TEMPLATE STYLES
    kaboomTextContainer: {
      position: 'absolute',
      top: 8,
      alignSelf: 'center',
      zIndex: 10,
    },
    kaboomTextMain: {
      fontFamily: Fonts.headings,
      fontSize: 34,
      fontWeight: '900',
      color: '#FFCD00',
      textShadowColor: '#000000',
      textShadowOffset: { width: 2, height: 2 },
      textShadowRadius: 1,
      letterSpacing: 0.5,
      transform: [{ rotate: '-6deg' }],
    },
    kaboomPlayerFrame: {
      width: 200,
      height: 200,
      position: 'absolute',
      alignSelf: 'center',
      top: 75,
      borderRadius: 100,
      borderWidth: 2,
      overflow: 'hidden',
      backgroundColor: 'rgba(255, 255, 255, 0.08)',
    },
    kaboomPlayerImage: {
      width: '100%',
      height: '100%',
    },
    kaboomSignatureContainer: {
      position: 'absolute',
      bottom: 42,
      alignSelf: 'center',
      alignItems: 'center',
      zIndex: 12,
    },
    kaboomPlayerNameText: {
      fontFamily: Fonts.headings,
      fontSize: 13,
      fontWeight: '900',
      color: '#FFFFFF',
      letterSpacing: 1,
      textShadowColor: '#000000',
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
    },
    kaboomInsertLabel: {
      fontFamily: Fonts.body,
      fontSize: 7,
      color: '#FFCD00',
      fontWeight: 'bold',
      letterSpacing: 0.5,
    },

    // DOWNTOWN TEMPLATE STYLES
    downtownPlayerFrame: {
      width: 170,
      height: 180,
      position: 'absolute',
      alignSelf: 'center',
      top: 80,
      overflow: 'hidden',
      zIndex: 5,
    },
    downtownPlayerImage: {
      width: '100%',
      height: '100%',
    },
    downtownTitleContainer: {
      position: 'absolute',
      bottom: 45,
      alignSelf: 'center',
      zIndex: 12,
    },
    downtownTitleText: {
      fontFamily: Platform.OS === 'ios' ? 'Snell Roundhand' : Platform.OS === 'web' ? 'Caveat' : 'cursive',
      fontSize: 32,
      color: '#047857',
      fontWeight: 'bold',
      textShadowColor: '#FFFFFF',
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
    },
  });
}

const lightStyles = createStyles(LightColors);
const darkStyles = createStyles(DarkColors as any);

export const summaryStyles = new Proxy({}, {
  get(target, prop) {
    const theme = useThemeStore.getState().theme;
    return theme === 'dark' ? darkStyles[prop as keyof typeof darkStyles] : lightStyles[prop as keyof typeof lightStyles];
  }
}) as ReturnType<typeof createStyles>;
