import { StyleSheet, Platform } from 'react-native';
import { Colors, Fonts, Spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
  keyboardContainer: {
    flex: 1,
    backgroundColor: Colors.obsidianBlack,
  },
  scrollContent: {
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.four,
    paddingBottom: Spacing.five,
    alignItems: 'center',
    gap: Spacing.three,
  },
  brandContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginTop: Spacing.two,
    width: '100%',
    maxWidth: 420,
  },
  titleTextContainer: {
    justifyContent: 'center',
  },
  brandTitleText: {
    fontFamily: Fonts.body,
    fontSize: 26,
    fontWeight: '900',
    color: Colors.primaryAccent,
    letterSpacing: -1.0,
  },
  cursiveGoldText: {
    color: Colors.hofYellow,
    fontFamily: Platform.select({
      web: "'Caveat', 'Dancing Script', cursive",
      default: 'System',
    }),
    fontSize: 32,
    fontWeight: 'bold',
    textTransform: 'none',
  },
  subtextKicker: {
    fontFamily: Fonts.stats,
    fontSize: 7,
    color: Colors.secondaryAccent,
    letterSpacing: 1.5,
    opacity: 0.7,
    marginTop: -2,
  },
  showcaseCard: {
    backgroundColor: 'rgba(24, 24, 27, 0.45)',
    borderColor: Colors.chromeSilver,
    borderWidth: 1,
    borderRadius: 12,
    padding: Spacing.three,
    width: '100%',
    maxWidth: 420,
    alignItems: 'center',
    gap: Spacing.two,
    ...Platform.select({
      web: {
        backdropFilter: 'blur(8px)',
      }
    })
  },
  slideIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: Colors.deepGraphiteCharcoal,
    borderColor: Colors.chromeSilver,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  slideTextGroup: {
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: Spacing.one,
  },
  slideKicker: {
    fontFamily: Fonts.stats,
    fontSize: 8,
    color: Colors.hofYellow,
    letterSpacing: 2,
    fontWeight: 'bold',
  },
  slideTitle: {
    fontFamily: Fonts.headings,
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.primaryAccent,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  slideDesc: {
    fontFamily: Fonts.body,
    fontSize: 10.5,
    color: Colors.secondaryAccent,
    textAlign: 'center',
    lineHeight: 14,
    opacity: 0.8,
  },
  dotIndicatorRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
    marginTop: 6,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#3f3f46',
  },
  errorBox: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderColor: Colors.status.danger,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    width: '100%',
    maxWidth: 420,
  },
  errorText: {
    fontFamily: Fonts.body,
    fontSize: 11,
    color: Colors.status.danger,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  socialAuthContainer: {
    width: '100%',
    maxWidth: 420,
    gap: 10,
  },
  socialButton: {
    height: 44,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    width: '100%',
  },
  appleButton: {
    backgroundColor: '#ffffff',
    borderColor: '#ffffff',
    borderWidth: 0,
  },
  googleButton: {
    backgroundColor: '#ffffff',
  },
  socialBtnText: {
    fontFamily: Fonts.body,
    fontSize: 13.5,
    fontWeight: '600',
    color: '#ffffff',
  },
  btnPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.985 }]
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    maxWidth: 420,
    gap: 12,
    marginVertical: 4,
  },
  line: {
    flex: 1,
    height: 1,
    backgroundColor: '#27272a',
  },
  dividerText: {
    fontFamily: Fonts.stats,
    fontSize: 8,
    color: '#52525b',
    letterSpacing: 1.5,
    fontWeight: '700',
  },
  formContainer: {
    width: '100%',
    maxWidth: 420,
    gap: Spacing.two,
  },
  inputGroup: {
    gap: 6,
    width: '100%',
  },
  inputLabel: {
    fontFamily: Fonts.stats,
    fontSize: 8,
    color: '#a1a1aa',
    letterSpacing: 1.2,
    fontWeight: 'bold',
  },
  textInput: {
    height: 44,
    backgroundColor: 'rgba(24, 24, 27, 0.6)',
    borderColor: '#3f3f46',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 14,
    fontSize: 13.5,
    color: '#ffffff',
    fontFamily: Fonts.body,
  },
  extendedFields: {
    gap: Spacing.two,
    width: '100%',
    marginTop: 2,
  },
  accountBadge: {
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 6,
    alignSelf: 'flex-start',
    borderWidth: 0.5,
  },
  badgeRegistered: {
    backgroundColor: 'rgba(255, 224, 102, 0.08)',
    borderColor: 'rgba(255, 224, 102, 0.25)',
  },
  badgeNew: {
    backgroundColor: 'rgba(34, 197, 94, 0.08)',
    borderColor: 'rgba(34, 197, 94, 0.25)',
  },
  badgeText: {
    fontFamily: Fonts.stats,
    fontSize: 7.5,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 2,
  },
  preferenceChip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: Colors.deepGraphiteCharcoal,
    borderColor: Colors.chromeSilver,
    borderWidth: 1,
    borderRadius: 20,
  },
  chipSelected: {
    borderColor: Colors.hofYellow,
    backgroundColor: 'rgba(255, 224, 102, 0.06)',
  },
  chipText: {
    fontFamily: Fonts.body,
    fontSize: 11,
    color: '#a1a1aa',
  },
  chipTextActive: {
    color: Colors.hofYellow,
    fontWeight: 'bold',
  },
  draftPosHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  draftPosVal: {
    fontFamily: Fonts.stats,
    fontSize: 9,
    color: Colors.hofYellow,
    fontWeight: 'bold',
  },
  selectorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 2,
  },
  selectorCell: {
    width: 44,
    height: 44,
    backgroundColor: Colors.deepGraphiteCharcoal,
    borderColor: Colors.chromeSilver,
    borderWidth: 1,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cellSelected: {
    borderColor: Colors.hofYellow,
    backgroundColor: 'rgba(255, 224, 102, 0.08)',
  },
  cellText: {
    fontFamily: Fonts.stats,
    fontSize: 11,
    color: '#a1a1aa',
  },
  cellTextActive: {
    color: Colors.hofYellow,
    fontWeight: 'bold',
  },
  ctaButton: {
    height: 48,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    marginTop: Spacing.two,
  },
  ctaLogin: {
    backgroundColor: Colors.liftedCharcoal,
    borderWidth: 1.5,
    borderColor: Colors.hofYellow,
  },
  ctaRegister: {
    backgroundColor: Colors.deepFieldGreen,
    borderWidth: 1,
    borderColor: 'rgba(224, 49, 34, 0.8)',
  },
  ctaButtonText: {
    fontFamily: Fonts.headings,
    fontSize: 13,
    color: '#ffffff',
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  ctaIcon: {
    marginLeft: 2,
  },
  onboardingFooter: {
    marginTop: Spacing.three,
    alignItems: 'center',
    gap: 4,
    width: '100%',
    paddingHorizontal: Spacing.three,
  },
  footerNoteText: {
    fontFamily: Fonts.body,
    fontSize: 9.5,
    color: '#52525b',
    textAlign: 'center',
  },
  footerVersionText: {
    fontFamily: Fonts.stats,
    fontSize: 7.5,
    color: '#3f3f46',
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  footerDevBtn: {
    marginTop: 12,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 224, 102, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 224, 102, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
  },
  footerDevBtnPressed: {
    backgroundColor: 'rgba(255, 224, 102, 0.12)',
    borderColor: Colors.hofYellow,
  },
  footerDevText: {
    fontFamily: Fonts.stats,
    fontSize: 9,
    fontWeight: 'bold',
    color: Colors.hofYellow,
    letterSpacing: 0.8,
  },
  socialNameForm: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: 'rgba(24, 24, 27, 0.45)',
    borderColor: Colors.chromeSilver,
    borderWidth: 1,
    borderRadius: 12,
    padding: Spacing.three,
    gap: Spacing.two,
  },
  socialFormTitle: {
    fontFamily: Fonts.headings,
    fontSize: 12,
    fontWeight: 'bold',
    color: Colors.hofYellow,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  socialFormActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  socialFormBtn: {
    flex: 1,
    height: 40,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  socialFormCancelBtn: {
    backgroundColor: 'transparent',
    borderColor: '#3f3f46',
    borderWidth: 1,
  },
  socialFormConfirmBtn: {
    backgroundColor: Colors.deepFieldGreen,
    borderColor: 'rgba(224, 49, 34, 0.8)',
    borderWidth: 1,
  },
  socialFormCancelText: {
    fontFamily: Fonts.stats,
    fontSize: 10,
    fontWeight: 'bold',
    color: '#a1a1aa',
    letterSpacing: 0.5,
  },
  socialFormConfirmText: {
    fontFamily: Fonts.stats,
    fontSize: 10,
    fontWeight: 'bold',
    color: '#ffffff',
    letterSpacing: 0.5,
  },
  forgotPasswordLinkText: {
    fontFamily: Fonts.stats,
    fontSize: 7.5,
    color: Colors.hofYellow,
    letterSpacing: 0.5,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  modalOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(9, 9, 11, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.four,
    zIndex: 10000,
  },
  modalContentCard: {
    backgroundColor: '#18181b',
    borderColor: '#27272a',
    borderWidth: 1,
    borderRadius: 12,
    padding: Spacing.four,
    width: '100%',
    maxWidth: 420,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  modalTitle: {
    fontFamily: Fonts.headings,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#ffffff',
    letterSpacing: 1,
  },
  modalDesc: {
    fontFamily: Fonts.body,
    fontSize: 10.5,
    color: '#a1a1aa',
    lineHeight: 15,
    marginBottom: Spacing.three,
  },
  modalErrorBox: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderColor: Colors.status.danger,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: Spacing.three,
  },
  modalErrorText: {
    fontFamily: Fonts.body,
    fontSize: 10.5,
    color: Colors.status.danger,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalFormGroup: {
    gap: 6,
    marginBottom: Spacing.three,
    width: '100%',
  },
  modalFormLabel: {
    fontFamily: Fonts.stats,
    fontSize: 8,
    color: '#a1a1aa',
    letterSpacing: 1.2,
    fontWeight: 'bold',
  },
  modalSingleLineInput: {
    height: 40,
    backgroundColor: 'rgba(24, 24, 27, 0.6)',
    borderColor: '#3f3f46',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 13,
    color: '#ffffff',
    fontFamily: Fonts.body,
  },
  modalActionRow: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'flex-end',
    marginTop: Spacing.two,
  },
  modalBtn: {
    height: 38,
    borderRadius: 8,
    paddingHorizontal: 16,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: '#3f3f46',
    borderWidth: 1,
  },
  modalBtnPrimary: {
    backgroundColor: Colors.deepFieldGreen,
    borderColor: 'rgba(224, 49, 34, 0.8)',
    borderWidth: 1,
    flex: 1,
  },
  modalBtnText: {
    fontFamily: Fonts.stats,
    fontSize: 9.5,
    fontWeight: 'bold',
    color: '#a1a1aa',
    letterSpacing: 0.5,
  },
  modalBtnTextPrimary: {
    fontFamily: Fonts.stats,
    fontSize: 9.5,
    fontWeight: 'bold',
    color: '#ffffff',
    letterSpacing: 0.5,
  },
});
