import { Platform } from 'react-native';

export interface NewsStoryItem {
  id: string;
  tag: 'BREAKING' | 'INJURY' | 'CONTRACT' | 'TRADE' | 'CAMP' | 'MARKET';
  tagColor: string;
  timeAgo: string;
  timestamp: number;
  headline: string;
  summary: string;
  take: string;
  playerName: string;
  position: 'QB' | 'RB' | 'WR' | 'TE' | 'K' | 'DST';
  team: string;
  trend: 'up' | 'down';
  imageUrl: string;
  localImage?: any; // Required local asset source
}

// Photography Studio Action Photo Maps
const localImages = {
  qb: require('../../assets/images/studio_qb.png'),
  rb: require('../../assets/images/studio_rb.png'),
  wr: require('../../assets/images/studio_wr.png'),
  te: require('../../assets/images/studio_te.png'),
};

export const SEEDED_NEWS_STORIES: NewsStoryItem[] = [
  {
    id: 'studio-news-1',
    tag: 'BREAKING',
    tagColor: '#EF4444',
    timeAgo: '15m ago',
    timestamp: Date.now() - 15 * 60 * 1000,
    headline: 'Anthony Richardson fires deep touchdowns, dominates first-team reps in Colts scrimmage',
    summary: 'Anthony Richardson looked absolutely electric in 11-on-11 contact drills today, launching multiple 40+ yard touchdown passes while displaying elite rushing mobility and zero limitations from his previous shoulder surgery.',
    take: 'Richardson has absolute top-3 fantasy QB upside in Shane Steichen\'s high-tempo RPO system. His rushing volume telemetry is elite. Secure him early in drafts to capture massive ADP arbitrage.',
    playerName: 'Anthony Richardson',
    position: 'QB',
    team: 'IND',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4685715.png&w=400&h=400',
    localImage: localImages.qb,
  },
  {
    id: 'studio-news-2',
    tag: 'CAMP',
    tagColor: '#bea98e',
    timeAgo: '45m ago',
    timestamp: Date.now() - 45 * 60 * 1000,
    headline: 'Justin Jefferson signs massive contract extension, reports to Vikings facilities immediately',
    summary: 'The long-awaited holdout is officially over. Justin Jefferson has signed a historic contract extension making him the highest-paid non-quarterback in NFL history. He is already participating in team walks.',
    take: 'Jefferson returns to full-speed camp drills. Any minor ADP dip during the contract negotiation window has closed. He is the undisputed WR1 overall in all PPR mock drafts.',
    playerName: 'Justin Jefferson',
    position: 'WR',
    team: 'MIN',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4260394.png&w=400&h=400',
    localImage: localImages.wr,
  },
  {
    id: 'studio-news-3',
    tag: 'INJURY',
    tagColor: '#fbbf24',
    timeAgo: '2h ago',
    timestamp: Date.now() - 2 * 60 * 60 * 1000,
    headline: 'Christian McCaffrey limited in practice due to minor hamstring tightness',
    summary: '49ers head coach Kyle Shanahan confirmed McCaffrey sat out team drills as a pure precaution. The coaching staff plans a light recovery workload for the remainder of the week.',
    take: 'Do not panic, but hamstring concerns are crucial for explosive backs. Draft Jordan Mason as an insurance policy in Round 12 to guarantee backfield dominance.',
    playerName: 'Christian McCaffrey',
    position: 'RB',
    team: 'SF',
    trend: 'down',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3117251.png&w=400&h=400',
    localImage: localImages.rb,
  },
  {
    id: 'studio-news-4',
    tag: 'TRADE',
    tagColor: '#22C55E',
    timeAgo: '4h ago',
    timestamp: Date.now() - 4 * 60 * 60 * 1000,
    headline: 'Saquon Barkley takes bulk of first-team redzone snaps in Eagles practice',
    summary: 'Barkley is displaying spectacular chemistry with Jalen Hurts in goal-line drills. The coaching staff is highlighting his vertical capacity, executing multiple screens out of the backfield.',
    take: 'Barkley behind this elite Philadelphia offensive line is a cheat code. His double-digit touchdown ceiling is locked in. Upgrade him to a premier Tier 1 running back.',
    playerName: 'Saquon Barkley',
    position: 'RB',
    team: 'PHI',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3925347.png&w=400&h=400',
    localImage: localImages.rb,
  },
  {
    id: 'studio-news-5',
    tag: 'CAMP',
    tagColor: '#bea98e',
    timeAgo: '6h ago',
    timestamp: Date.now() - 6 * 60 * 60 * 1000,
    headline: 'Sam LaPorta showing elite target shares in Lions redzone packages',
    summary: 'Lions offensive coordinator Ben Johnson has designed multiple tight-end screen wrinkles specifically for LaPorta, who continues to look like Jared Goff\'s favorite goal-line weapon.',
    take: 'LaPorta is the real deal. In a crowded Detroit offense, his redzone target concentration guarantees elite weekly TE viability. A safe target at his current high ADP.',
    playerName: 'Sam LaPorta',
    position: 'TE',
    team: 'DET',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4430587.png&w=400&h=400',
    localImage: localImages.te,
  },
  {
    id: 'studio-news-6',
    tag: 'MARKET',
    tagColor: '#c084fc',
    timeAgo: '9h ago',
    timestamp: Date.now() - 9 * 60 * 60 * 1000,
    headline: 'CeeDee Lamb active in Cowboys facility; expected to see massive target volume',
    summary: 'Dak Prescott and CeeDee Lamb connected on several deep passes in live simulated situations. The team intends to force-feed Lamb in standard and slot alignments this season.',
    take: 'Lamb\'s projected target volume remains historically high. He is a premier top-3 overall draft anchor. Calibrate your cheat sheets to lock him in as an elite WR core.',
    playerName: 'CeeDee Lamb',
    position: 'WR',
    team: 'DAL',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4241389.png&w=400&h=400',
    localImage: localImages.wr,
  },
  {
    id: 'studio-news-7',
    tag: 'CAMP',
    tagColor: '#bea98e',
    timeAgo: '12h ago',
    timestamp: Date.now() - 12 * 60 * 60 * 1000,
    headline: 'Breece Hall flashes elite explosiveness, makes full recovery from knee soreness',
    summary: 'Hall participated fully in first-team scrimmages, showcasing his trademark cuts and high-speed breakaway runs. The Jets staff reported no soreness or setbacks.',
    take: 'Hall is a top-2 running back in all formats. His receiving floor is incredibly secure, especially with Aaron Rodgers back under center. Lock him in early.',
    playerName: 'Breece Hall',
    position: 'RB',
    team: 'NYJ',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4430852.png&w=400&h=400',
    localImage: localImages.rb,
  },
  {
    id: 'studio-news-8',
    tag: 'TRADE',
    tagColor: '#22C55E',
    timeAgo: '18h ago',
    timestamp: Date.now() - 18 * 60 * 60 * 1000,
    headline: 'Marvin Harrison Jr. dominates Cardinals first-team snaps, showing instant rookie connection',
    summary: 'Kyler Murray and Marvin Harrison Jr. hook up on three separate deep sideline throws. Coaches praise the rookie wideout\'s coverage diagnosis and massive catch radius.',
    take: 'Harrison Jr. has the target path to immediately enter the WR1 conversation. Do not hesitate to pick him in the late second round; his elite skill ceiling justifies the price.',
    playerName: 'Marvin Harrison Jr.',
    position: 'WR',
    team: 'ARI',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4683062.png&w=400&h=400',
    localImage: localImages.wr,
  },
  {
    id: 'studio-news-9',
    tag: 'BREAKING',
    tagColor: '#EF4444',
    timeAgo: '1d ago',
    timestamp: Date.now() - 24 * 60 * 60 * 1000,
    headline: 'Patrick Mahomes focuses on deep connections with rookie Xavier Worthy in Chiefs camp',
    summary: 'Worthy\'s record-breaking speed was on display as Mahomes completed several deep bombs down the sideline. Andy Reid is utilizing Worthy in multiple pre-snap motions.',
    take: 'Mahomes gets his explosive deep vertical weapon back. This elevates Mahomes\' overall quarterback grading and makes Worthy a high-upside sleeper in all drafts.',
    playerName: 'Patrick Mahomes',
    position: 'QB',
    team: 'KC',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3139477.png&w=400&h=400',
    localImage: localImages.qb,
  },
  {
    id: 'studio-news-10',
    tag: 'CAMP',
    tagColor: '#bea98e',
    timeAgo: '1d ago',
    timestamp: Date.now() - 28 * 60 * 60 * 1000,
    headline: 'Tyreek Hill dominates speed drills, looks fully primed for another 1,700-yard push',
    summary: 'Hill was clocked at a blistering 21.8 mph during camp sprints today. Mike McDaniel\'s motion offense is heavily prioritizing Hill in dynamic wideout screens.',
    take: 'Hill\'s target floor is completely bulletproof in Miami. He remains an elite first-round choice who can single-handedly win matchups. Track his ADP accordingly.',
    playerName: 'Tyreek Hill',
    position: 'WR',
    team: 'MIA',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3116406.png&w=400&h=400',
    localImage: localImages.wr,
  },
  {
    id: 'studio-news-11',
    tag: 'INJURY',
    tagColor: '#fbbf24',
    timeAgo: '1d ago',
    timestamp: Date.now() - 32 * 60 * 60 * 1000,
    headline: 'Jahmyr Gibbs sits out Lions practice with minor hamstring strain',
    summary: 'Gibbs was seen working on the sideline with trainers. Head coach Dan Campbell clarified that it is a minor strain and they will exercise extreme caution in the pre-season.',
    take: 'A minor blow to Gibbs\' early momentum, elevating David Montgomery\'s initial role. Gibbs remains an elite talent, but this tightness makes Montgomery an amazing middle-round steal.',
    playerName: 'Jahmyr Gibbs',
    position: 'RB',
    team: 'DET',
    trend: 'down',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4430737.png&w=400&h=400',
    localImage: localImages.rb,
  },
  {
    id: 'studio-news-12',
    tag: 'CAMP',
    tagColor: '#bea98e',
    timeAgo: '2d ago',
    timestamp: Date.now() - 48 * 60 * 60 * 1000,
    headline: 'Amon-Ra St. Brown showcases unmatched target volume, catching 15 straight in camp scrimmage',
    summary: 'St. Brown was Jared Goff\'s constant security blanket today, moving the chains repeatedly in third-down situational scrimmages and showing outstanding route precision.',
    take: 'The "Sun God" has one of the safest target volume ceilings in all of fantasy football. Lock him in as a high-floor WR1 in all PPR or Half-PPR formats.',
    playerName: 'Amon-Ra St. Brown',
    position: 'WR',
    team: 'DET',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4361546.png&w=400&h=400',
    localImage: localImages.wr,
  },
  {
    id: 'studio-news-13',
    tag: 'CAMP',
    tagColor: '#bea98e',
    timeAgo: '2d ago',
    timestamp: Date.now() - 52 * 60 * 60 * 1000,
    headline: 'Drake London sees heavy target volume, operates as undisputed WR1 in Falcons new offense',
    summary: 'New Falcons offensive coordinator Zac Robinson is heavily utilizing London across the formations, feeding him slant-routes and deep posts from veteran Kirk Cousins.',
    take: 'London is primed for a colossal breakout campaign under an improved quarterback setup. His target share is elite, making him a major value at current ADP metrics.',
    playerName: 'Drake London',
    position: 'WR',
    team: 'ATL',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4426514.png&w=400&h=400',
    localImage: localImages.wr,
  },
  {
    id: 'studio-news-14',
    tag: 'MARKET',
    tagColor: '#c084fc',
    timeAgo: '3d ago',
    timestamp: Date.now() - 72 * 60 * 60 * 1000,
    headline: 'Travis Kelce looking exceptionally sharp, showing elite redzone telemetries with Mahomes',
    summary: 'Chiefs coordinators are managing Kelce\'s physical reps, but in high-priority redzone drills he remains completely unstoppable. Mahomes connected with him for three touchdowns.',
    take: 'Despite age-model projections, Kelce\'s elite scoring share and volume safety make him a prime tight-end anchor. Grab him confidently as a draft cornerstone.',
    playerName: 'Travis Kelce',
    position: 'TE',
    team: 'KC',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/15847.png&w=400&h=400',
    localImage: localImages.te,
  },
  {
    id: 'studio-news-15',
    tag: 'CAMP',
    tagColor: '#bea98e',
    timeAgo: '3d ago',
    timestamp: Date.now() - 76 * 60 * 60 * 1000,
    headline: 'Ja\'Marr Chase details strong physical progress in training camp drills with Joe Burrow',
    summary: 'Burrow and Chase demonstrated absolute harmony on deep back-shoulder throws today. Chase appears fully conditioned and highly motivated for a dominant season.',
    take: 'Chase\'s chemistry with Burrow is a legendary fantasy engine. If he slides slightly due to target competition, jump immediately. Lock in this elite WR1 asset.',
    playerName: 'Ja\'Marr Chase',
    position: 'WR',
    team: 'CIN',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4432708.png&w=400&h=400',
    localImage: localImages.wr,
  },
  {
    id: 'studio-news-16',
    tag: 'CAMP',
    tagColor: '#bea98e',
    timeAgo: '4d ago',
    timestamp: Date.now() - 96 * 60 * 60 * 1000,
    headline: 'Lamar Jackson showcases lightning speed, operates Ravens new passing schemes cleanly',
    summary: 'Jackson made several spectacular tight-window throws to Zay Flowers and Isaiah Likely, while keeping defensive coordinators off-balance with high-density rushing scrambles.',
    take: 'Jackson is an elite dual-threat engine whose high weekly floor guarantees elite quarterback viability. Draft confidently for top-tier production metrics.',
    playerName: 'Lamar Jackson',
    position: 'QB',
    team: 'BAL',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3916387.png&w=400&h=400',
    localImage: localImages.qb,
  },
  {
    id: 'studio-news-17',
    tag: 'TRADE',
    tagColor: '#22C55E',
    timeAgo: '4d ago',
    timestamp: Date.now() - 100 * 60 * 60 * 1000,
    headline: 'Kyren Williams maintains dominant grip on Rams first-team backfield snaps',
    summary: 'Rams head coach Sean McVay continues to feed Williams as the absolute primary workhorse back. Despite the addition of Blake Corum, Williams dominated all goal-line rushes.',
    take: 'Williams\' redzone volume and offensive scoring role are secure. While Corum adds minor security depth, Williams is a locked-in high-value RB1 choice.',
    playerName: 'Kyren Williams',
    position: 'RB',
    team: 'LAR',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4426362.png&w=400&h=400',
    localImage: localImages.rb,
  },
  {
    id: 'studio-news-18',
    tag: 'CAMP',
    tagColor: '#bea98e',
    timeAgo: '5d ago',
    timestamp: Date.now() - 120 * 60 * 60 * 1000,
    headline: 'Garrett Wilson develops spectacular redzone connection with Aaron Rodgers',
    summary: 'Wilson caught four touchdowns during redzone simulations today. Rodgers repeatedly targeted him in tight windows, praising Wilson\'s elite lateral separation.',
    take: 'Wilson is primed for a monster target breakout with Rodgers under center. His technical skillset and target consolidation make him a lock for WR1 tiering.',
    playerName: 'Garrett Wilson',
    position: 'WR',
    team: 'NYJ',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4430816.png&w=400&h=400',
    localImage: localImages.wr,
  },
  {
    id: 'studio-news-19',
    tag: 'MARKET',
    tagColor: '#c084fc',
    timeAgo: '5d ago',
    timestamp: Date.now() - 124 * 60 * 60 * 1000,
    headline: 'Puka Nacua displays elite physical conditioning, catching deep passes from Stafford',
    summary: 'Nacua showed absolute full health, running sharp routes and locking down contested catches. Sean McVay has designed several new slot-motion looks for him.',
    take: 'Nacua\'s historic rookie season was no fluke. He remains an elite, high-volume receiving option in this high-scoring Rams passing attack. Draft with confidence.',
    playerName: 'Puka Nacua',
    position: 'WR',
    team: 'LAR',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4403307.png&w=400&h=400',
    localImage: localImages.wr,
  },
  {
    id: 'studio-news-20',
    tag: 'CAMP',
    tagColor: '#bea98e',
    timeAgo: '6d ago',
    timestamp: Date.now() - 144 * 60 * 60 * 1000,
    headline: 'Trey McBride operates as primary intermediate threat in Cardinals camp drills',
    summary: 'McBride was Murray\'s constant middle-of-the-field checkdown option, logging heavy targets during simulated scrimmage sessions. His speed in pads wowed coordinators.',
    take: 'McBride is an elite target hog at the tight-end position. While Harrison Jr. stretches the field, McBride owns the middle. A superb target for draft value.',
    playerName: 'Trey McBride',
    position: 'TE',
    team: 'ARI',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4361413.png&w=400&h=400',
    localImage: localImages.te,
  },
  {
    id: 'studio-news-21',
    tag: 'CAMP',
    tagColor: '#bea98e',
    timeAgo: '6d ago',
    timestamp: Date.now() - 148 * 60 * 60 * 1000,
    headline: 'Bijan Robinson sees heavy usage as hybrid receiver in Falcons training camp',
    summary: 'Falcons coaches lined Robinson up as a slot receiver on multiple plays today. Robinson made several dynamic catches, demonstrating elite route running and footwork.',
    take: 'Bijan Robinson is an absolute dual-threat fantasy titan. Under a modernized coaching staff, his heavy receiving integration makes him a premier overall draft asset.',
    playerName: 'Bijan Robinson',
    position: 'RB',
    team: 'ATL',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4430807.png&w=400&h=400',
    localImage: localImages.rb,
  },
  {
    id: 'studio-news-22',
    tag: 'BREAKING',
    tagColor: '#EF4444',
    timeAgo: '1w ago',
    timestamp: Date.now() - 168 * 60 * 60 * 1000,
    headline: 'De\'Von Achane takes first-team backfield snaps, demonstrating blazing speeds in pads',
    summary: 'Achane repeatedly gashed the secondary in camp drills today, displaying his elite speed and quick burst holes. The Dolphins intend to scale his touches in high-value zones.',
    take: 'Achane\'s historic efficiency metrics makes him a legendary fantasy game-changer. Despite split-backfield concerns, his explosive scoring potential is worth every penny.',
    playerName: 'De\'Von Achane',
    position: 'RB',
    team: 'MIA',
    trend: 'up',
    imageUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4372016.png&w=400&h=400',
    localImage: localImages.rb,
  }
];

export function getPhotographyFeed(): NewsStoryItem[] {
  // Always sort chronologically to deliver a live, constantly feeding collection
  return [...SEEDED_NEWS_STORIES].sort((a, b) => b.timestamp - a.timestamp);
}
